databases:
  - name: salonsite
    databaseName: salonsite
    user: salonsite_user

services:
  - type: web
    name: salonRailsAPI
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: salonsite
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false